#!/bin/sh
#

BOOKTITLE="Get Started on Linux by End of Tonight"
BOOKSUBTITLE="Without Breaking Your Box &#8211; A Userbie Guide"

##################
# define minibook
##################

# define book as directories in certain order

add_mod chapter vagrant
add_mod chapter man_pages
add_mod chapter work_with_directories
add_mod chapter work_with_files
add_mod chapter work_with_file_contents
