#!/bin/sh
#

BOOKTITLE="Get Started on Linux in 45 Minutes"
BOOKSUBTITLE="Intro to the Shell"

##################
# define minibook
##################

# define book as directories in certain order

add_mod chapter man_pages
add_mod chapter working_with_directories
add_mod chapter working_with_files
add_mod chapter working_with_file_contents
